### DISCUSSION TITLE
App-Selector not working for me

### DISCUSSION THREAD

**Discussion by micxba** [RoadieHQ/roadie-backstage-plugins#1182] [General]
I have multiple deployment targets for my component (dev/stage/prod) and I would like all of them shown via the plugin.
Another user said he solved this with app selectors but that does not seem to work for me. I tried multiple ways but e.g.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-dev
  namespace: argocd
  labels:
   appname: myapp
...
```

The in the catalog I'd try something like
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: myapp
  annotations:
    argocd/app-selector: appname=myapp
```

But this results in `Error occurred while fetching data. Error: failed to fetch data, status 504: Gateway Timeout` within Backstage.

I might be completely off somewhere here but any guidance is appreciated.
