### DISCUSSION TITLE
RAG IA - tech-docs embeddings

### DISCUSSION THREAD

**Discussion by herbergt** [RoadieHQ/roadie-backstage-plugins#1353] [Q&A]
Hi,

I'm trying to set the Backstage tech docs as embeddings, I'm executing the request shown below
![image](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/13681841/1d90bc32-2dc1-489b-8ec7-704af6516c6c)

I have registered a component into Backstage with the [Backstage tech-docs](https://github.com/backstage/backstage/tree/master/docs) in order to have enough data to embed into the model, however, when I ask something related to backstage the response is very naive, seems that is not taking into consideration the tech-docs data.

![image](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/13681841/eae8c159-2397-4cba-915f-b23aa996ac7a)

The embeddings table seems to have just data related to the Backstage components, I cannot see any reference to tech-docs data

```json
{"kind": "Component", "source": "catalog", "splitId": "1", "entityRef": "component:default/my-component"}
```

**IA Config**
```yaml
# Roadie RAG AI configuration
ai:
  supportedSources: ['catalog']
  embeddings:
    # AWS Bedrock Embeddings configuration
    bedrock:
      # (Required) Name of the Bedrock model to use to create Embeddings.
      modelName: 'amazon.titan-embed-text-v1'`
```
Am I missing something? Is the embedding of tech-docs implemented or is it something that I need to implement?
