### DISCUSSION TITLE
Help with filter for the catalog-backend-module-okta plugin

### DISCUSSION THREAD

**Discussion by wywilliamyang9** [RoadieHQ/roadie-backstage-plugins#1740] [Q&A]
The following is the current config I have in the app-config:
```
providers:
    okta:
      - orgUrl: 'https://fico.okta.com'
        token: ${OKTA_TOKEN}
        groupFilter: profile.name eq "Backstage_Users"
        schedule:
          frequency:
            seconds: 20
          timeout:
            minutes: 10
          initialDelay:
            seconds: 45
```
It is pulling only the group `Backstage_Users` and pulling all the users in my org. Ideally, I want to pull only the users in the group `Backstage_Users` and all the groups in okta so the users can be assigned to the groups that they are assigned to in okta. Could someone help with this? For the userFilter, I tried `memberof eq "Backstage_Users"` but that is not valid.
