### DISCUSSION TITLE
ArgoCD: How to map appLocatorMethods.instances[] to catalog-info.yaml?

### DISCUSSION THREAD

**Discussion by rodgomes** [RoadieHQ/roadie-backstage-plugins#529] [Q&A]
Hi all, 

I was reading this docs about having multiple instances of argoCD running and was not sure how the mapping works:
https://roadie.io/backstage/plugins/argo-cd/#support-for-multiple-argo-cd-instances---option-2---argo-cd-backend-plugin

What is not clear is how I connect my application from the catalog, with the instances described in 
```
appLocatorMethods:
    - type: 'config'
      instances:
        - name: Instance1
```

Or in other words, do I need to tell in my catalog-config.yaml the instance name(s) of the argocd? If not, how does the mapping happen? 

Thanks a lot for your help and for making the plugin available!
