### DISCUSSION TITLE
Does roadie scaffolder-backend-module-http-request support authorization in headers?

### DISCUSSION THREAD

**Discussion by subash54** [RoadieHQ/roadie-backstage-plugins#745] [Q&A] [answered]
Hi Team I am using **roadie scaffolder-backend-module-http-request** to call api which has authentication

```
 - id: backstage_request_with_input
      name: backstage request
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/api/proxy/sheet/test'
      headers:
        Authorization: 'Basic c3ViYXNoOmhlbGxv'
```
The above is the body that I am passing but I am getting unauthorized  while passing authorization in headers.

In Postman for the same I am able to send the request.

Whether it supports passing authorization in headers.

 Can anyone help me in this?
