### DISCUSSION TITLE
http:backstage:request :> How can i still have '/api' in my path attribute for http:request action

### DISCUSSION THREAD

**Discussion by Nitinvonage** [RoadieHQ/roadie-backstage-plugins#952] [Q&A]
Recently i moved to latest Backstage version 1.12.1 and therefore also bumped roadies "@roadiehq/scaffolder-backend-module-http-request" plugin to 4.0.5.

Because of this update my software templates which are using http:backstage:request action are not working. Its because of the path i am passing to it.

```
- id: get_information
      name: Fetch Information
      action: http:backstage:request
      input:
        method: 'GET'
        **path: '/api/catalog/entities/by-name/domain/${{ parameters.domain.split('':'')[1] }}'**
```
I have used this action in many templates, >20. would there be a configurable way to not manually remove **/api** from the path
I think this has been changed because the http:Request plugin in now consuming **discoveryAPI**

still if there is a configurable way, it would be more easy for us.
