### ISSUE TITLE
Looking for Dynamic Datadog Dashboard

### ISSUE THREAD

**Issue by RSchandra** [RoadieHQ/roadie-backstage-plugins#1005]
## Feature Suggestion

With respect to datadog URL, we provide the below config in app-config.yaml file, in-order for the dashboard to be visible on application's backstage page
```
backend:
 csp:
     frame-src: 
     # Allow your Datadog URL for @roadiehq/backstage-plugin-datadog
     - 'us.datadoghq.com'
     - 'app.us.datadoghq.com'
     - '<DATADOG_DASHBOARD_SOURCE>'
```

But if we need to add for multiple applications, how can we provide dynamic  <DATADOG_DASHBOARD_SOURCE>  in order for it be used for multiple project with different "<DATADOG_DASHBOARD_SOURCE>".
 
For example, I have 10 dashboards for 10 different project(One for each project respectively). Now, we would like to show the respective Datadog dashboard in their respective backstage integration. How can we achieve it dynamically
