### ISSUE TITLE
Docs | typo in scaffolder utils readme

### ISSUE THREAD

**Issue by larszi** [RoadieHQ/roadie-backstage-plugins#1014]
Inside the docs the wrong step is referred to  inside the output

```
  steps:
    - id: parsefile
      name: Parse File
      action: roadiehq:utils:fs:parse
      input:
        path: ${{ parameters.path }}
        parser: ${{ parameters.parser }}
  output:
    content: ${{ steps.serialize.output.content }}
```

## Expected Behavior

The readme should refer to the correct step inside the output

```
output:
    content: ${{ steps.parsefile.output.content }}
```
## Steps to Reproduce

Copy & Paste the current example into an Backstage Template,
When copy & pasteing  example around this can easily lead to mistakes
