### ISSUE TITLE
Allow for default mkdocs.yaml

### ISSUE THREAD

**Issue by wrighbr** [RoadieHQ/roadie-backstage-plugins#1050]
## Feature Suggestion
Starting from version 1.11.0, Backstage now includes a default mkdoc.yaml file  https://github.com/backstage/backstage/pull/15417
Add the ability to pass validation when the following annotation is set
```
apiVersion: backstage.io/v1alpha1
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
```

## Possible Implementation
on line https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/utils/roadie-backstage-entity-validator/src/relativeSpaceValidation.js#L24 add a or statement to check for `dir:.`

## Context
relates to https://github.com/RoadieHQ/backstage-entity-validator/issues/69
