### ISSUE TITLE
[scaffolder-backend-module-utils] Transforming yaml

### ISSUE THREAD

**Issue by athifongoqa** [RoadieHQ/roadie-backstage-plugins#1089]
I am trying to take a yaml file and basically append to an existing list. I followed the docs but it does not seem to change the file upon creating a PR with it later. Am I missing something?

The file should be updated in the workspace then used in the PR. 

## Current Behavior

The PR is created with the file unchanged. 

## Steps to Reproduce

```
    - id: fetch-flux
          name: Fetch Flux Base
          action: fetch:template
          input:
            url: ./helm/maps
            targetPath: ./flux
            values:
              component_id: ${{ parameters.component_id }}
              description: ${{ parameters.description }}

    - id: fetch-remote-flux-kustomization
      name: Fetch Flux stg env
      action: fetch:plain
      input:
        url: https://github.com/ORG/flux-cd/tree/main/stg
        targetPath: ./flux-remote

    - id: move-flux-stg-kustomization
      action: fs:rename
      name: Move stg env kustomization
      input:
        files:
          - from: ./flux-remote/kustomization.yaml
            to: ./flux/kustomization.yaml

    - id: transform-ks
      name: Transform Kustomization
      action: roadiehq:utils:jsonata:yaml:transform
      input:
        path: ./flux/kustomization.yaml
        expression: '$ ~> | $ | { "resources": [items, "../base/${{ parameters.component_id }}"] }|'

    - id: pr-as-it-flux
      name: PR Flux
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=flux-cd&owner=ORG
        sourcePath: ./flux
        branchName: '${{ parameters.component_id }}'
        title: 'chore: add ${{ parameters.component_id }}'
        description: 'chore: add ${{ parameters.component_id }} release'

```

I want to append another workload dynamically in this yaml file at resources:

```
apiversion: v1
kind: Kustomization
resources: 
    - workload-one
    - workload-two
patch:
    - patch-one

```

## Your Environment

"@backstage/backend-common": "^0.19.2",
    "@backstage/backend-tasks": "^0.5.5",
    "@backstage/catalog-client": "^1.4.3",
    "@backstage/catalog-model": "^1.4.1",
    "@backstage/config": "^1.0.8",
    "@backstage/integration": "^1.6.0",
    "@backstage/plugin-adr-backend": "^0.3.6",
    "@backstage/plugin-app-backend": "^0.3.48",
    "@backstage/plugin-auth-backend": "^0.18.6",
    "@backstage/plugin-auth-node": "^0.2.17",
    "@backstage/plugin-catalog-backend": "^1.12.0",
    "@backstage/plugin-catalog-backend-module-github": "^0.3.3",
    "@backstage/plugin-code-coverage-backend": "^0.2.14",
    "@backstage/plugin-kubernetes-backend": "^0.11.3",
    "@backstage/plugin-permission-backend": "^0.5.23",
    "@backstage/plugin-permission-common": "^0.7.7",
    "@backstage/plugin-permission-node": "^0.7.11",
    "@backstage/plugin-playlist-backend": "^0.3.4",
    "@backstage/plugin-proxy-backend": "^0.3.0",
    "@backstage/plugin-scaffolder-backend": "^1.16.1",
    "@backstage/plugin-search-backend": "^1.4.0",
    "@backstage/plugin-search-backend-module-pg": "^0.5.9",
    "@backstage/plugin-search-backend-node": "^1.2.4",
    "@backstage/plugin-sonarqube-backend": "^0.2.2",
    "@backstage/plugin-techdocs-backend": "^1.6.5",
    "@frontside/scaffolder-yaml-actions": "^0.1.3",
    "@roadiehq/scaffolder-backend-module-utils": "^1.10.2",
    "app": "link:../app",
    "dockerode": "^3.3.4",
    "express": "^4.18.2",
    "express-promise-router": "^4.1.1",
    "pg": "^8.8.0",
    "winston": "^3.8.2"
