### ISSUE TITLE
[scaffolder-backend-module-utils]  resolve variables in `roadiehq:utils:fs:append` action content

### ISSUE THREAD

**Issue by ichasco-heytrade** [RoadieHQ/roadie-backstage-plugins#1099]
Hi, It's possible to resolve the variables using `roadiehq:utils:fs:append` action?

For example:
```
    - id: append-argocd-config
      name: Add config to ArgoCD Config File
      action: roadiehq:utils:fs:append
      input:
        path: ./helm/argocd-apps/${{ parameters.env }}.yaml
        content: |
              # *** ${{ upper(parameters.name) }} ***
              - name: ${{ parameters.name }}
                namespace: ${{ parameters.properties }}
                valueFiles:
                  - values.yaml
                  - ${{ parameters.lifecycle }}.yaml
                #disableFinalizer: "true"
                ignoreDifferences:
                  - group: apps
                    kind: ${{ parameters.type }}
                    jsonPointers:
                      - /spec/replicas
```

This I need to transform to variablized text. Is there any way to do this?

Thanks!
