### ISSUE TITLE
Make the append action able to read from one file and merge it with another.

### ISSUE THREAD

**Issue by alejandraRamos** [RoadieHQ/roadie-backstage-plugins#1128]
## Feature Suggestion
We need the capability to utilize the `roadiehq:utils:fs:append` action for merging an existing file into another by providing a path.
Something similar to this:

```
- id: mergeMonitors
  name: Merge monitors
  action: roadiehq:utils:fs:append
  input:
    path: "./monitoring/${{ parameters.teamOwner.split('/') | last() }}.tf"
    content: "skeletons/terraform/resource/main.tf"
```
Because currently, content field only allows text `content`, not the path to another file.

## Possible Implementation

The plugin could look like this:
```
- id: mergeMonitors
  name: Merge monitors
  action: roadiehq:utils:fs:append
  input:
    path: "./monitoring/${{ parameters.teamOwner.split('/') | last() }}.tf"
    content: "skeletons/terraform/resource/main.tf"
```
The idea is that the `content` attribute can receive the path to a file, not just text. This way we can merge two files into one.

## Context
I'm building a Backstage component that creates Datadog alarms based on the service and some specified parameters. These monitors will be grouped into a file representing the team's name.

I need to be able to add multiple Terraform resources associated with different services in the same file, considering a skeleton where I define the resource to create the alarm using the parameters exported by the Backstage component through `fetch:template.`
