### ISSUE TITLE
Data is not  loading and giving 404 with No project could be found with key 

### ISSUE THREAD

**Issue by Saiprasad2021** [RoadieHQ/roadie-backstage-plugins#1194]
## Expected Behavior
 it should open the plugin UI with number of stories bug and tasks.

## Current Behavior
  throwing error with 404 
  {"errorMessages":["No project could be found with key 'JFAI'."],"errors":{}}

![image](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/53864113/f631d5d2-4d13-4edc-ba75-2214ec7213a3)

## Steps to Reproduce
 updated the relevant config items i.e token and jira url

## Context
   The api respons it self not getting. getting error message with 
   
![image](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/53864113/af0f60c5-f7d2-4208-96ef-c92346524916)

## Your Environment

- `@backstage/plugin-catalog-react` version:^1.8.5
- `@backstage/integration` version: 
i have     "@backstage/integration-react": "^1.1.20",
instead of     "@backstage/integration:

**Comment by beakable** [comment]
Seeing the same issue, this output can be reproduced via the JIRA API directly via curl if I remove the provided Basic auth., perhaps auth isn't applying correctly with the plugin?

**Comment by roman-shandurenko** [comment]
I found an issue in my project @Saiprasad2021 .

1. Go to your [account settings](https://id.atlassian.com/manage-profile/security/api-tokens) and generate your API token.
2. Then [base64 encode](https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/#supply-basic-auth-headers) it: on Mac/Linux `echo -n user@example.com:api_token_string | base64`
3. Update proxy config in `app-config.yaml` - pay attention to correct indentation:
```yml
    '/jira/api':
      target: 'https://XXX.atlassian.net'
      headers:
        Authorization: ${JIRA_TOKEN}
        Accept: 'application/json'
        Content-Type: 'application/json'
        X-Atlassian-Token: 'nocheck'
        User-Agent: 'AnyDummyString'
```
4. Re-run the app to pick up new configs.
