### ISSUE TITLE
Output of HTTP Request action not rendering as expected

### ISSUE THREAD

**Issue by jsidney** [RoadieHQ/roadie-backstage-plugins#1231]
I am trying to use the `http:backstage:request` plugin to run specific HTTP requests when scaffolding a repo  from a template (eg: registering a new project on sonarqube) but I cannot easily tell if the request is being successful as the output from the module seems  to not render correctly.
## Expected Behavior
I am expecting that when I have an output block in my `template.yaml`, that the output should be a json string of an HTTP response. 

eg:
```yaml
...
steps:
    - id: sonarqube_request
      name: sonarqube request
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/proxy/sonarqube/projects/search'
...
  output:
    text:
      - title: Name of Template
        content: |
          ${{ parameters.name }}
      - title: Response 
        content: |
          ${{ steps.sonarqube_request.output.body }}
      - title: Code
        content: |
          ${{ steps.sonarqube_request.output.code }}
      - title: Headers 
        content: |
          ${{ steps.sonarqube_request.output.headers }}
```
should render with the body and headers as json strings. 

## Current Behavior
Howver, right now, when I try and use the `output.body` or `output.headers`, all that is rendered in the output is: "[Object, object]

![image](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/7551131/2faf075f-414b-45f4-b1d3-b4d5de1bf04c)

## Your Environment

- `@backstage/plugin-catalog-react` version: 1.9.3
- `@roadiehq/scaffolder-backend-module-http-request` version: ^4.1.1
