### ISSUE TITLE
argocd:create-resources: unable to verify the first certificate

### ISSUE THREAD

**Issue by cmoulliard** [RoadieHQ/roadie-backstage-plugins#1232]
## Issue

Is there a way to by pass such a TLS Certificate issue `reason: unable to verify the first certificate` when we create a new argocd resource using the action

```
    - id: create-argocd-resources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{ parameters.component_id }}-bootstrap
        argoInstance: argocdQShift # Match appconfig => argocd/appLocatorMethods/instances/name
        namespace: ${{ parameters.namespace }}
        repoUrl: ${{ steps.publish.output.remoteUrl }}
        labelValue: ${{ parameters.name }}
        path: 'argocd/'
```

Error reported
```
2024-01-25T12:03:02.000Z Beginning step Create ArgoCD Resources22024-01-25T12:03:02.000Z FetchError: request to https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev//api/v1/session, Opens in a new window failed, reason: 
unable to verify the first certificate3    at 
ClientRequest.<anonymous> (/opt/app-root/src/dynamic-plugins-root/roadiehq-scaffolder-backend-argocd-dynamic/node_modules/node-fetch/lib/index.js:1501:11)4    at 
ClientRequest.emit (node:events:517:28)5    at 
TLSSocket.socketErrorListener (node:_http_client:501:9)6    at 
TLSSocket.emit (node:events:517:28)7    at 
emitErrorNT (node:internal/streams/destroy:151:8)8    at 
emitErrorCloseNT (node:internal/streams/destroy:116:3)9    at 
process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
