### ISSUE TITLE
ArgoCD plugin regression: `EntityArgoCDHistoryCard` doesn't work when ArgoCD backend plugin is used

### ISSUE THREAD

**Issue by tumido** [RoadieHQ/roadie-backstage-plugins#1238]
There seems to be a regression since `2.5.0` of the ArgoCD frontend plugin. The `EntityArgoCDHistoryCard` fails to load and disappears if the plugin used together with ArgoCD backend plugin.

## Expected Behavior

The card loads fine

## Current Behavior

In `2.5.0` and `2.5.1` the card disappears after loading, without error in console, or anywhere else.

## Steps to Reproduce

Install to `packages/app`:

```
    "@roadiehq/backstage-plugin-argo-cd": "2.5.1",
```

Install to `packages/backend`:

```
    "@roadiehq/backstage-plugin-argo-cd-backend": "2.14.0",
```

Mount `EntityArgoCDHistoryCard`

https://github.com/RoadieHQ/roadie-backstage-plugins/assets/7453394/37442f02-2f1e-48d5-a1ff-3297a3e1f879

What is also quite interesting, the component disappears without any errors logged to the console. No errors are reported whatsoever.

## Context

When I downgrade the frontend package to 
```
    "@roadiehq/backstage-plugin-argo-cd": "2.4.1",
```

It all works again:

https://github.com/RoadieHQ/roadie-backstage-plugins/assets/7453394/3c0fa248-e82f-4d0f-a1e4-60316f0478f5

## Your Environment

- `@backstage/plugin-catalog-react` version: `1.9.3`
- `@backstage/integration` version: `1.8.0`

**Comment by cmoulliard** [comment]
The issue is more complex than what it is reported here as the frontend app-config is colliding with the backend config

If we configure the proxy like this + what it is needed for the backend
```
argocd:
  baseUrl: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/
  username: admin
  password: hU5ksdnFxK...7BGQDEX
  
AND

proxy:
  endpoints:
    '/argocd/api':
      target: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/api/v1
      changeOrigin: true
      secure: false
      headers:
        Cookie:
          argocd.token=eyJhbGc  ...
```
then we can see the argocd UI views + data as reported by @tumido  
BUT the scaffolding is failing as we don't set the fields as such: 
```
argocd:
  baseUrl: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev
  username: admin
  password: hU5...QDEX
  appLocatorMethods:
    - type: config
      instances:
        - name: argocdQShift
          url: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev
```

If now, we configure for the front and backend the fields as such:
```
proxy:
  endpoints:
    '/argocd/api':
      target: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/api/v1
      changeOrigin: true
      secure: false
      headers:
        Cookie:
          argocd.token=eyJhbGciOi...2Mk6TVMPT8lYnyI

argocd:
  baseUrl: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev
  username: admin
  password: hU5k...GQDEX
  appLocatorMethods:
    - type: config
      instances:
        - name: argocdQShift
          url: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev
```
then, we can scaffold a project BUT we cannot see the data within the Argocd UI views
