### ISSUE TITLE
add regex support for roadiehq:utils:fs:replace

### ISSUE THREAD

**Issue by hpgrahsl** [RoadieHQ/roadie-backstage-plugins#1244]
The scaffolder action roadiehq:utils:fs:replace is for some reason not supporting/allowing replacements which are regex-based.

## Feature Suggestion

For certain cases, it would be very helpful to have regex support which is explicitly not in the current scope. There is even a code comment about no regex usage see here https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/scaffolder-actions/scaffolder-backend-module-utils/src/actions/fs/replaceInFile.ts#L86-L87

## Possible Implementation

I think for reasons of not breaking existing configurations this additional feature should be implemented in a backwards compatible way. Alternatively, a separate action could be introduced which is explicitly used for regex-based find/replace operations in case the existing one isn't meant to support both standard and regex based replacements.

## Context

Use a regex-based find/replacement to modify existing files.

**Comment by hpgrahsl** [comment]
I think it's worth keeping this "alive" hence this comment :-)

**Comment by alecsammon** [comment]
I created a PR to implement this here: https://github.com/RoadieHQ/roadie-backstage-plugins/pull/1393

Uses `matchRegex: bool` to modify the behaviour of the existing `roadiehq:utils:fs:replace`.

**Comment by hpgrahsl** [comment]
THX @alecsammon. Highly appreciated!

**Comment by kkanchev** [comment]
@alecsammon Are there any examples of how this is being used? I played around with it but could not get it to work. How is the expression look like in the find 🤔 I tried to set it in a template for replacing an orb but it does not seem to match, although if I use "orbs:" without a regex it finds it.
```
- id: set-orb
      name: Set CircleCI Orb
      action: roadiehq:utils:fs:replace
      input:
        files:
          - file: ./.circleci/config.yml
            find: /^orbs:$/i
            matchRegex: true
            replaceWith: |
              orbs:
                some-orb: some-orb/orb@${{ parameters.orb }}
```

**Comment by alecsammon** [comment]
@kkanchev  - My guess would be this is due to the way the regex is treated when extracting from yaml and passing to the JS method.

I think that the "find" will be treated as a string - so instead of being passed to JS as `new Regexp(/^orbs:$/i, 'g')` it will be `new Regexp('/^orbs:$/i', 'g')`.

As such instead of being evaluated as `/^orbs:$/i` it will be `/\/^orbs:$\/i/g` - hence it doesn't match as you expect.

I think you will have to pass the value as `find: ^orbs:$` - but this does mean you won't be able to use the `i` flag. It might be that this plugin needs to be updated to allow for another field of `flags` so you can do 

```
          - file: ./.circleci/config.yml
            find: ^orbs:$
            flags: 
              - i
            matchRegex: true
```

Or an more user friendly and compatible idea might be to have
```
          - file: ./.circleci/config.yml
            find: ^orbs:$
            caseInsensitiveMatch: true
            matchRegex: true
```
