### ISSUE TITLE
[Argo CD Plugin] Can be set a different Dashboard URL than the API URL

### ISSUE THREAD

**Issue by mugioka** [RoadieHQ/roadie-backstage-plugins#1291]
In my environment, for security purposes, the domain of the Argo CD Server that provides the dashboard and the domain of the Argo CD Server that provides the API are separate like bellow:

Client -- dashboard.development.example.com --> Load Balancer(Enabled [IAP](https://cloud.google.com/security/products/iap?hl=ja)) --> Argo CD Server

Backstage Server  -- api.development.example.com --> Load Balancer(Enabled IP restriction using [Cloud Armor](https://cloud.google.com/security/products/armor?hl=ja) and only serve /api/v1/*) --> Argo CD Server

The Argo CD Plugin is configured as follows:

```yaml
argocd:
  namespacedApps: true
  appLocatorMethods:
    - type: "config"
      instances:
        - name: development
          url: https://api.development.example.com
          token: ${ARGOCD_AUTH_TOKEN_DEV}
        - name: staging
          url: api.staging.example.com
          token: ${ARGOCD_AUTH_TOKEN_STG}
```

In this configuration, the link to the Argo CD UI that appears in the Backstage UI is to the Argo CD Server that provides the API(api.development.example.com/api.staging.example.com), which is not what we want.
https://github.com/RoadieHQ/roadie-backstage-plugins/blob/d14e7f16497284cd8e6642cd88b7acfa6bd98feb/plugins/frontend/backstage-plugin-argo-cd/src/components/DetailsDrawer.tsx#L80

## Feature Suggestion

I think it would be better if the link to the Argo CD Server that appears in the Backstage UI could be different from the one used when using the API.

## Possible Implementation

I think it would be good to modify [getBaseUrl](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/d14e7f16497284cd8e6642cd88b7acfa6bd98feb/plugins/frontend/backstage-plugin-argo-cd/src/components/ArgoCDDetailsCard.tsx#L172-L185) to allow different Dashboard URLs to be set for each Argo CD instance, as shown below.

```yaml
argocd:
  namespacedApps: true
  appLocatorMethods:
    - type: "config"
      instances:
        - name: development
          url: https://api.development.example.com
          dashboardUrl: https://dashboard.development.example.com
          token: ${ARGOCD_AUTH_TOKEN_DEV}
        - name: staging
          url: api.staging.example.com
          dashboardUrl: https://dashboard.staging.example.com
          token: ${ARGOCD_AUTH_TOKEN_STG}
```
