### ISSUE TITLE
An action to create an ArgoCD repository

### ISSUE THREAD

**Issue by dmartinol** [RoadieHQ/roadie-backstage-plugins#1298]
The `argocd:create-resources` action cannot access private repos. A similar action may be added to configure the repository secret from the same software template.

## Feature Suggestion
Possible action configuration for `git `repo connected with SSH:
```yaml
      name: Create the ArgoCD repository
      action: argocd:create-repository
      input:
        project: myproject
        type: git
        url: git@github.com:RoadieHQ/roadie-backstage-plugins.git
        sshPrivateKey: <base64 encoded string>
```
## Possible Implementation
Follow the  [CreateRepositoryCredentials API](https://cd.apps.argoproj.io/swagger-ui#operation/RepoCredsService_CreateRepositoryCredentials) to define the payload (e.g. the action input).

FYI, @masayag @gciavarrini @pkliczewski
