### ISSUE TITLE
@roadiehq/scaffolder-backend-module-utils to handle multiple documents in the same catalog file

### ISSUE THREAD

**Issue by rgubby** [RoadieHQ/roadie-backstage-plugins#1305]
If you have multiple documents in the same catalog file, such as 
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: Test
  tags:
    - abc

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  tags: def
```

when you try and use the `roadiehq:utils:merge` action to merge content (lets say i wanted to add another item to `tags`), you get a YAML error:

```
Source contains multiple documents; please use YAML.parseAllDocuments() at line 50, column 1:
```

## Feature Suggestion

Allow multiple documents in the same catalog file to be parsed.

## Possible Implementation

Switch https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/scaffolder-actions/scaffolder-backend-module-utils/src/actions/merge/merge.ts#L224 to use `YAML.parseAllDocuments` instead of `YAML.parse` and merge everywhere - also do the same for JSON source.

## Context

I'm trying to merge new content in an action with multiple docs.
