### ISSUE TITLE
RAG Plugin - Cannot use 'in' operator to search for 'metadata' in undefined

### ISSUE THREAD

**Issue by herbergt** [RoadieHQ/roadie-backstage-plugins#1336]
I have configured The RAG plugin according to the documentation for [frontend](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/frontend/rag-ai/README.md) and [backend](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/backend/rag-ai-backend/README.md) components.

## Expected Behavior

RAG Dialog should show the response to the query.

## Current Behavior

I'm able to enter the query

![image](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/13681841/c446c379-835f-4615-8261-7bad97d57e9a)

The backend call is successful

![image](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/13681841/ebd3ed46-5a3f-415c-98a9-0f6816d5711f)

``` yaml 
{
  "response": " The schema name for the metadata is your_metadata_db.",
  "embeddings": [
    {
      "content": "form-k8s-state/tree/main/teams/mayorg/applications/hasura/\",\"backstage.io/kubernetes-id\":\"hasura\",\"backstage.io/techdocs-ref\":\"dir:.\"},\"name\":\"hasura\",\"links\":[{\"url\":\"https://hasura.qa.mayorg.com\",\"title\":\"Hasura",
      "metadata": {
        "kind": "Component",
        "source": "catalog",
        "splitId": "1",
        "entityRef": "component:default/hasura"
      }
    },
    {
      "content": "{\"metadata\":{\"namespace\":\"default\",\"annotations\":{\"backstage.io/managed-by-location\":\"url:https://github.com/myorg/mayorgk8s-state/tree/main/teams/mayorg/applications/hasura/catalog-info.yaml\",\"backstage.io/managed-by-origin-location\":\"url:https://github.com/myorg/mayorgk8s-state/blob/main/teams/mayorg/applications/hasura/catalog-info.yaml\",\"backstage.io/view-url\":\"https://github.com/myorg/mayorgk8s-state/tree/main/teams/mayorg/applications/hasura/catalog-info.yaml\",\"backstage.io/edit-url\":\"https://github.com/myorg/mayorgk8s-state/edit/main/teams/mayorg/applications/hasura/catalog-info.yaml\",\"backstage.io/source-location\":\"url:https://github.com/myorg/mayorgk8s-state/tree/main/teams/mayorg/applications/hasura/\",\"backstage.io/kubernetes-id\":\"hasura\",\"backstage.io/techdocs-ref\":\"dir:.\"},\"name\":\"hasura\",\"links\":[{\"url\":\"https",
      "metadata": {
        "kind": "Component",
        "source": "catalog",
        "splitId": "0",
        "entityRef": "component:default/hasura"
      }
    }
   
  ]
}
```

The frontend fails when trying to render the response:

![image](https://github.com/RoadieHQ/roadie-backstage-plugins/assets/13681841/143cc953-ef18-4e7b-bd54-d6871a888f64)

I have noticed that the error only happens when the indexing of the catalog data is finished, If I ask a question when the indexing is not finished the dialog displays the answer correctly.

## Your Environment

- `@backstage/plugin-catalog-react` version: 1.9.3
- `@backstage/integration-react` version: 1.1.23
- `@backstaget` version: 1.22.2
