### ISSUE TITLE
ArgoCD Dashboard link button not working properly for multiple ArgoCD instances

### ISSUE THREAD

**Issue by adityasinghal26** [RoadieHQ/roadie-backstage-plugins#1344]
When using multiple ArgoCD instances using `@roadiehq/backstage-plugin-argo-cd-backend`, I am able to fetch the ArgoCD applications from multiple instances. However, the `Link` button redirects to only of the ArgoCD instance URL for all applications.

## Expected Behavior
The `Link` button should update the `baseUrl` for `Open ArgoCD Dashboard` hyperlink based on instance.

## Current Behavior
The `Link` button for both instances redirects to the same ArgoCD instance.

## Steps to Reproduce
1. Configure multiple ArgoCD instances and install the above package in your backend package. Make sure that you don't specify any `argocd.baseUrl` parameters in `app-config.yaml` file.

```
argocd:
  appLocatorMethods:
    - type: 'config'
      instances:
        - name: Instance1
          url: https://instance1-argocd.wiprotops.com
          token: ${ARGOCD_AUTH_TOKEN} # optional
        - name: Instance2
          url: https://instance2-argocd.wiprotops.com
          token: ${ARGOCD_AUTH_TOKEN2} # optional
```
2. Configure a Backstage component with below annotation for an `appName` that exists in both ArgoCD instances.

```
metadata:
  name: example-website
  annotations:
        argocd/app-selector: app.kubernetes.io/app=appName
```
3. Start the server and go over to your ArgoCD tab to see something like below.

<img width="1391" alt="image" src="https://github.com/RoadieHQ/roadie-backstage-plugins/assets/11928122/61693c51-e8d7-4c81-b229-141e5a0dd5cb">

## Possible Solution
I have went through the code for the particular use case. I can see that the `baseUrl` gets updated based on whether multiple instances and `argocd.baseUrl` are configured in `app-config.yaml`. However, I am still running into the above issue.

Link to code: [https://github.com/RoadieHQ/roadie-backstage-plugins/blob/bee37f8ea1281c595fc5d0352076cd560b8a50a4/plugins/frontend/backstage-plugin-argo-cd/src/components/ArgoCDDetailsCard.tsx#L172](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/bee37f8ea1281c595fc5d0352076cd560b8a50a4/plugins/frontend/backstage-plugin-argo-cd/src/components/ArgoCDDetailsCard.tsx#L172)

## Context
We have multiple ArgoCD instances for different environments of the same application. Due to this, we would like to redirect the user to the respective ArgoCD instance based on the environment which they are trying to access.

## Your Environment

- `@backstage/plugin-catalog-react` version:  "^1.10.0",
- `@roadiehq/backstage-plugin-argo-cd` version: "^2.5.1",
- `@roadiehq/backstage-plugin-argo-cd-backend` version: "^2.14.7",
