### ISSUE TITLE
plugin: github-insights ERROR

### ISSUE THREAD

**Issue by savez** [RoadieHQ/roadie-backstage-plugins#145]
Hi,
I installed the plugin (https://roadie.io/backstage/plugins/github-insights) in my backstage but I recive an error:"The github.com/project-slug annotation is missing. You need to add the annotation to your component if you want to enable this tool.”

In my component the annotation is present

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cdn
  description: CDN
  annotations:
    github.com/project-slug: savez/cdn
```

How can i solve the problem?
