### ISSUE TITLE
YAML actions' `options` field is broken

### ISSUE THREAD

**Issue by bensaine-coveo** [RoadieHQ/roadie-backstage-plugins#1462]
[This PR](https://github.com/RoadieHQ/roadie-backstage-plugins/pull/1241) which changes the YAML module used under the hood has broken the `options` field for YAML-related actions. 

## Expected Behavior
```yaml
- id: merge
  name: Merge
  action: roadiehq:utils:merge
  input:
    path: ./template.yaml
    content: >
      foo: [bar, baz, qux]
    options:
      flowLevel: 1
```  
should produce
```yaml
...
foo: [bar, baz, qux]
```
 
## Current Behavior
```yaml
- id: merge
  name: Merge
  action: roadiehq:utils:merge
  input:
    path: ./template.yaml
    content: >
      foo: [bar, baz, qux]
    options:
      flowLevel: 1
```  
wrongfully produces
```yaml
...
foo:
  - bar
  - baz
  - qux
```

## Steps to Reproduce
See above.

## Possible Solution
Re-define the `options` object to match the new `yaml`'s module options schema.

## Context

This is happening because the `options` object is [passed directly to the underlying module](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/9684eb1480dd3586b7a320724a7b90d3d192c360/plugins/scaffolder-actions/scaffolder-backend-module-utils/src/actions/merge/merge.ts#L251), which used to be `js-yaml` - see https://github.com/nodeca/js-yaml?tab=readme-ov-file#dump-object---options-. Since the module has change to `yaml`, options are no longer the same, so `flowLevel` doesn't mean anything to `yaml` - see https://eemeli.org/yaml/#tostring-options.
