### ISSUE TITLE
Aliases get renamed as *a

### ISSUE THREAD

**Issue by billyatroadie** [RoadieHQ/roadie-backstage-plugins#1591]
When I use the merge action, it renames my aliases to *a<index> with <index> being a number

## Expected Behavior

aliases and anchors stay as they are

## Current Behavior
See above

## Steps to Reproduce

Using this yaml as config.yaml: 
```
hello-world: &hello-world
  run:
    name: Hello World
    command: |
      echo "hello world!"
jobs:
  hello-universe:
    steps:
      - *hello-world
```

and this action:

    - id: format-config
      name: Format
      action: roadiehq:utils:merge
      input:
        path: 'config.yml'
        content: {}
        mergeArrays: true
        preserveYamlComments: true
        options:
          lineWidth: 0
          blockQuote: 'literal'
          sortKeys: true

## Possible Solution
https://github.com/eemeli/yaml/issues/105 check this out and see if that's the issue?
## Context
This [issue](https://github.com/eemeli/yaml/issues/105) states that it should be using parseDocument vs parse, but I'm not sure if that's even accurate.

## Your Environment

- `@backstage/plugin-catalog-react` version: 1.12.2
- `@backstage/integration` version: 1.13.0
