### ISSUE TITLE
[Prometheus plugin] Issue with Prometheus Alert

### ISSUE THREAD

**Issue by hoanglecao** [RoadieHQ/roadie-backstage-plugins#1689]
Hi Team,

I am using the Prometheus plugin to integrate Backstage with Prometheus and I am encountering an 'Unexpected token' issue

## Current Behavior

When configuring Prometheus with a cloud-hosted instance using proxy settings, I encountered the following error when viewing Prometheus Alerts: <i><b>Unexpected token 'd', 'demopromet' is not valid JSON</b></i>

## Steps to Reproduce
```yaml
   // app-config.yaml
proxy:
  endpoints:
    '/prometheus/api':
      target: ${PROMETHEUS_URL}
      credentials: dangerously-allow-unauthenticated // I am using it to avoid the 401 Unauthorized error, which I had previously posted about here: https://github.com/RoadieHQ/roadie-backstage-plugins/issues/1680
      headers:
        Authorization: Basic ${PROMETHEUS_TOKEN}
```
```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    prometheus.io/rule: 'demoprometheus'
    prometheus.io/alert: "demoprometheus-01"
```
I am trying to debug and found that the issue occurs when executing the API below

![image](https://github.com/user-attachments/assets/0c7f185d-ba7b-429a-9a05-0b221db32dab)

I am not sure what I am missing or if I have misconfigured something. Any suggestions or ideas would be greatly appreciated.

## My Environment

- "@backstage/plugin-catalog-react": "workspace:^",
- `"@backstage/integration-react": "workspace:^":
- "@roadiehq/backstage-plugin-prometheus": "^2.11.3",
