### ISSUE TITLE
[Prometheus plugin] Fetch should incorporate proxy authentication.

### ISSUE THREAD

**Issue by ipe4647** [RoadieHQ/roadie-backstage-plugins#1710]
## Feature Suggestion

The proxy usage should be authenticated so that anyone can't use the path /api/proxy/prometheus/api. Prometheus in production has such safeguards with Bearer token and Backstage plugin should implement it as well.

## Possible Implementation

Add identityApiRef to the query (this is an example; all places that interact with the proxy should use authentication):
https://github.com/RoadieHQ/roadie-backstage-plugins/blob/b59b4b48ed09a8a214825c7e7d50004e06ae3b80/plugins/frontend/backstage-plugin-prometheus/src/api/index.ts#L106-L113

Some example code:
```
  // Obtain the token
  const { token: idToken } = await identityApi.getCredentials();
 // Fetch with authentication
  const response = await fetch( 
     `${apiUrl}/query_range?query=${query}&start=${start}&end=${end}&step=${step}`, 
     { 
       headers: { 
         [SERVICE_NAME_HEADER]: serviceName || '', 
         Authorization: `Bearer ${idToken}`,
       }, 
     }, 
   ); 
```
## Context

Right now the workaround is to use ` credentials: dangerously-allow-unauthenticated` (#1680) that removes authentication.
This change will make proxy secure by allowing access only to authenticated users and does not expose Prometheus to the network.

This issue might be tied with security vulnerability as the proxied system is exposed to unauthenticated users.

**Comment by marknet15** [comment]
Still an issue I can confirm I see the same problem, at my company we have multiple Prometheus instances and defining anymore than the `1` instance under `instances` trips up on the errors on config.

So this works:
```yaml
proxy:
  endpoints:
    '/prometheusa/api':
      target: 'https://prom-a/api/v1/'
      credentials: dangerously-allow-unauthenticated
    '/prometheusb/api':
      target: 'https://prom-b/api/v1/'
      credentials: dangerously-allow-unauthenticated

prometheus:
  proxyPath: /prometheusa/api
  uiUrl: https://prom-a
  instances:
    - name: prometheusToolingUK
      proxyPath: /prometheusb/api
      uiUrl: https://prom-b
```

But anymore under `instances` and it fails.
