### ISSUE TITLE
[Backstage AI Assistant] Is this plugin already compatible with the new backend system?

### ISSUE THREAD

**Issue by gabriel-dantas98** [RoadieHQ/roadie-backstage-plugins#1749]
I noticed that in the documentation the examples are in the old standard.

https://roadie.io/backstage/plugins/ai-assistant-rag-ai/

## Feature Suggestion

If it is already compatible with the new backend system, we can update the documentation.

And if you still have to use the legacy form, how would the implementation be?

**Comment by gabriel-dantas98** [comment]
Maybe @Irma12 has some updates?

**Comment by dfl-aeb** [comment]
We'd love to use this plugin but the missing documentation is a real pain. Any change to get this updated?

**Comment by dfl-aeb** [comment]
In case anyone else is still looking for a solution, i managed to get it up and running with these forked packages:

```ts
// rag-ai plugin
backend.add(import('@alithya-oss/plugin-rag-ai-backend'));
backend.add(import('@alithya-oss/plugin-rag-ai-backend-module-openai'));
```

Thanks to [alithya](https://github.com/alithya-oss/backstage-plugins/tree/main/workspaces/rag-ai)

**Comment by leuenbert** [comment]
@dfl-aeb would you be able to provide a more detailed look on your implementation for the new backend, how you got it up and running?

**Comment by dfl-aeb** [comment]
Actually that was pretty much it. Simply install the packages from [alithya](https://github.com/alithya-oss/backstage-plugins/tree/main/workspaces/rag-ai) in the backend, install the frontend part (i used the original from roadie `import { RagModal } from '@roadiehq/rag-ai';`) and execute the [create-embeddings.js](https://github.com/alithya-oss/backstage-plugins/blob/main/workspaces/rag-ai/create-embeddings.js) as described [here](https://github.com/alithya-oss/backstage-plugins/blob/main/workspaces/rag-ai/README.md#create-embedings).


Ah and i had to replace my local postgres with this pgvector-db:

```yaml
version: '3.8'
services:
  pgvector:
    hostname: postgres
    image: ankane/pgvector
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
```
