### ISSUE TITLE
RAG AI: Seeking advice for optimising model and parameter tweaking for best results with backstage catalog

### ISSUE THREAD

**Issue by hexionas** [RoadieHQ/roadie-backstage-plugins#1778]
Hey guys.

I am working with the RAG AI plugin and I have successfully got it to work with AWS Bedrock. I am very new to the space of LLMs and I just wanted to ask in the community if anyone has some advice about tweaking the parameters to give better results when asking the AI certain things about the catalog.

Do you have any combinations of embedding model / prompt models that work well with specific parameters for embedding/chunking etc? The current setup I have makes the prompt responses quite useless, with lots of hallucinating and just in general incorrect information. 

My main use case is to reliably retrieve information from API definitions to generate some basic code snippets, or just to get information about how some entities are related to each other. Currently when generating embeddings I run into a lot of Throttling exceptions even on a single entity in backstage - I am unsure how to handle that particular problem - I guess for that single entity there is just far too many embeddings being generated.

Here is a sample of the config I am currently running with:
```yaml
# Roadie RAG AI configuration
ai:
  supportedSources: ['catalog', 'tech-docs']

  storage:
    pgvector:
      # (Optional) The size of the chunk to flush when storing embeddings to the DB. Defaults to 500
      chunksize: 800

  embeddings:
    chunkSize: 800

    # (Optional) The overlap between adjacent chunks of embeddings. The bigger the number, the more overlap. Defaults to 200
    chunkOverlap: 700

    bedrock:
      # (Required) Name of the Bedrock model to use to create Embeddings.
      modelName: 'amazon.titan-embed-text-v1'
      maxTokens: 1024
      maxRetries: 10
```

```typescript
  const model = new Bedrock({
    maxTokens: 1024,
    model: 'amazon.titan-text-express-v1',
    region: 'eu-central-1',
    credentials: credProvider.sdkCredentialProvider,
  });
```
