### ISSUE TITLE
Unable to insert parameter values as object keys with roadiehq:utils:merge

### ISSUE THREAD

**Issue by jackmtpt** [RoadieHQ/roadie-backstage-plugins#1809]
## Expected Behavior

Scaffolder step:

```yaml
- id: injectPipeline
  name: Merge pipeline definition
  action: roadiehq:utils:merge
  input:
    path: ./my.file.yml
    preserveYamlComments: true
    content: {
      "pipelines": {
        "${{ parameters.serviceFullName }}": {
          "yml_path": "./pipelines/${{ parameters.serviceShortName }}.yml"
        }
      }
    }
```

Suppose that:

-  `serviceFullName ` = `My.Service`
- `serviceShortName` = `my-service`

Existing file contents:

```yaml
pipelines:
  ExamplePipe1:
    yml_path: pipeline.yml
```

I expect the final file to be:

```yaml
pipelines:
  ExamplePipe1:
    yml_path: pipeline.yml
  My.Service:
    yml_path: ./pipelines/my-service.yml
```

## Current Behavior

Instead I get this:

```yaml
pipelines:
  ExamplePipe1:
    yml_path: pipeline.yml
  ${{ parameters.serviceFullName }}:
    yml_path: ./pipelines/my-service.yml
```

The serviceFullName parameter reference is left as the literal ${{ }} string - it's not substituted at all.

- `"@roadiehq/scaffolder-backend-module-utils": "^3.0.0"
- Backstage `1.33.2`

**Comment by jackmtpt** [comment]
Specifying the `content` as a YAML object rather than JSON also doesn't work:

```yaml
content:
  pipelines: 
    ${{ parameters.serviceFullName }}:
      yml_path: ./pipelines/${{ parameters.serviceShortName }}.yml
```

However specifying it as as string _does_ work:

```yaml
content: |
  pipelines: 
    ${{ parameters.serviceFullName }}:
      yml_path: ./pipelines/${{ parameters.serviceShortName }}.yml
```
