### ISSUE TITLE
plugin-prometheus: Multiple Prometheus instances not working.

### ISSUE THREAD

**Issue by vv-itsvit** [RoadieHQ/roadie-backstage-plugins#1823]
## Expected Behavior

When we add 2 more prometheus instances, we can get graph from differents prometheus instances use the annotation prometheus.io/service-name.

```yaml
# app.config.yaml
proxy:
  '/prometheus/api':
    target: http://localhost:9090/api/v1/
  '/prometheusTeamB/api':
    target: http://localhost:9999/api/v1/
  '/prometheusTeamС/api':
    target: http://localhost:9998/api/v1/

prometheus:
  proxyPath: /prometheus/api
  uiUrl: http://localhost:9090
  instances:
    - name: prometheusTeamB
      proxyPath: /prometheusTeamB/api
    - name: prometheusTeamC
      proxyPath: /prometheusTeamС/api
```

## Current Behavior

When I add 2 more prometheus instances  in app.config.yaml, build and start dev   I get error:
`[backend]: ForwardedError: Plugin 'app' startup failed; caused by Error: Invalid app bundle schema. If this error is unexpected you need to run `yarn build` in the app. If that doesn't help you should make sure your config schema is correct and rebuild the app bundle again. Caused by the following schema error, Error: Config validation failed, Config must NOT have more than 1 items { limit=1 } at /prometheus/instances
`

## Steps to Reproduce

1. Add 2 or more `prometheus.instances` 
2. Build  `yarn build:backend`
3. Start app `yarn dev `

## Possible Solution

Fix instances in `backstage-plugin-prometheus/config.d.ts`:

```ts
  ...
    instances?: Array<{
        /**
         * The proxy service instance name.
         * Should match the annotation prometheus.io/service-name.
         * @visibility frontend
         */
        name: string;
        /**
         * The proxy path for the service instance.
         * Should match a Backstage proxy.
         * @visibility frontend
         */
        proxyPath: string;
        /**
         * The URL for the Prometheus UI.
         * @visibility frontend
         */
        uiUrl?: string;
      }>,
    ...
```

## Your Environment

- `@backstage/plugin-catalog-react` version:
- `@backstage/integration` version:

**Comment by marknet15** [comment]
I can confirm I see the same problem, at my company we have multiple Prometheus instances and defining anymore than the `1` instance under `instances` trips up on the errors on config.

So this works:
```yaml
proxy:
  endpoints:
    '/prometheusa/api':
      target: 'https://prom-a/api/v1/'
      credentials: dangerously-allow-unauthenticated
    '/prometheusb/api':
      target: 'https://prom-b/api/v1/'
      credentials: dangerously-allow-unauthenticated

prometheus:
  proxyPath: /prometheusa/api
  uiUrl: https://prom-a
  instances:
    - name: prometheusToolingUK
      proxyPath: /prometheusb/api
      uiUrl: https://prom-b
```

But anymore under `instances` and it fails.
