### ISSUE TITLE
scaffolder-backend-module-utils: version 3.2.0 - Multiple documents found in the input content.

### ISSUE THREAD

**Issue by winkbrian** [RoadieHQ/roadie-backstage-plugins#1831]
After updating to 3.3.0, my scaffolder actions began to fail with the error:

**Error: Multiple documents found in the input content. Please provide a key and value to use to find the document to merge into.**

My yaml file is only a single document, so the new version is somehow interpreting it as multiple even though it is only one. I tried to use a key/value pair to identify my document, but this did not work wither. 

Perhaps because I have no top level key/value pairs I couldn't get the `useDocumentIncludingField` option to work for me.

I was able to workaround by downgrading to 3.1.0

## Expected Behavior

Single document yamls should merge without issue

## Current Behavior

Single document yaml is being seen as multiple documents and so the merge fails with error **Error: Multiple documents found in the input content. Please provide a key and value to use to find the document to merge into.**

## Steps to Reproduce

Here is an example of what I am trying to merge

Original
```yaml
---
application:
  environment: "dev"
  parameters:
    memory: 512M
    cores: 1
  server:
    - name: example1
      port: 8080
options:
  something:
    enabled: true
```

What I want to merge in
```yaml
---
application:
  server:
    - name: example2
      port: 8081
```

## Possible Solution

Instead of trying to determine if a yaml file has multiple documents, make it a flag or only read it that way if the `useDocumentIncludingField` is set

## Context

Unable to update plugin past 3.1.0

## Your Environment

- `@backstage/plugin-catalog-react`: version: latest
- `@backstage/integration` version: latest
