### ISSUE TITLE
roadiehq:utils:merge now considers empty file invalid yaml

### ISSUE THREAD

**Issue by madsteer** [RoadieHQ/roadie-backstage-plugins#1841]
We'd been running `@roadiehq/scaffolder-backend-module-utils` version `3.0.1` for a few months.  We recently tried to update to latest `3.3.0/3.4.0` but when we did, we could no longer get the `roadiehq:utils:merge` action to work if the `path` file was empty.  We were able to update to version `3.1.0` but starting with `3.2.0` we experienced the error

## Expected Behavior

merge action adds new yaml content to empty file with `*.yaml` file extension.

## Current Behavior

we get the following error and stacktrace:
```shell
2025-02-28T16:39:42.796Z Error: No documents found in the input content. Please provide a valid YAML file.[90](http://localhost:3000/create/tasks/f7924c45-f676-49f4-a165-02387e6f9fe5#line-90)    
at checkDocumentExists (/dev/git/pde/backstage/node_modules/@roadiehq/scaffolder-backend-module-utils/src/actions/merge/merge.ts:394:11)[91](http://localhost:3000/create/tasks/f7924c45-f676-49f4-a165-02387e6f9fe5#line-91)    
at mergeDocumentsRemovingComments (/dev/git/pde/backstage/node_modules/@roadiehq/scaffolder-backend-module-utils/src/actions/merge/merge.ts:326:3)[92](http://localhost:3000/create/tasks/f7924c45-f676-49f4-a165-02387e6f9fe5#line-92)    
at Object.handler (dev/git/pde/backstage/node_modules/@roadiehq/scaffolder-backend-module-utils/src/actions/merge/merge.ts:298:31)[93](http://localhost:3000/create/tasks/f7924c45-f676-49f4-a165-02387e6f9fe5#line-93)    
at NunjucksWorkflowRunner.executeStep (/dev/git/pde/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:387:22)[94](http://localhost:3000/create/tasks/f7924c45-f676-49f4-a165-02387e6f9fe5#line-94)    
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[95](http://localhost:3000/create/tasks/f7924c45-f676-49f4-a165-02387e6f9fe5#line-95)    
at async NunjucksWorkflowRunner.execute (/dev/git/pde/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:533:9)[96](http://localhost:3000/create/tasks/f7924c45-f676-49f4-a165-02387e6f9fe5#line-96)    
at async TaskWorker.runOneTask (/dev/git/pde/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:205:26)[97](http://localhost:3000/create/tasks/f7924c45-f676-49f4-a165-02387e6f9fe5#line-97)   
 at async run (/dev/git/pde/backstage/node_modules/p-queue/dist/index.js:163:29)[98](http://localhost:3000/create/tasks/f7924c45-f676-49f4-a165-02387e6f9fe5#line-98)
2025-02-28T16:39:42.796Z error: No documents found in the input content. Please provide a valid YAML file.
```

## Steps to Reproduce

Create a scaffolder template that includes a step like so:
```yaml
 # Update the plugin yaml if config vars are needed
    - id: update-plugin-config
      name: Update plugin yaml
      if: ${{ parameters.configVarsDep == true }}
      action: roadiehq:utils:merge
      input:
        path: plugins/${{ parameters.name }}/plugin-${{ parameters.name }}.yaml
        content: |
          some:
             simple: yaml
```
to attempt to add. yaml content to an empty file
## Context

Are having to remain at an older version of ``@roadiehq/scaffolder-backend-module-utils`, version `3.1.0`

## Your Environment

- `@backstage/plugin-catalog-react` version: `resolution: "@backstage/plugin-catalog-react@npm:1.15.2"` from yarn.lock
- `@backstage/integration` version: `resolution: "@backstage/integration@npm:1.16.1"` from yarn.lock
