### ISSUE TITLE
Support multiple GitHub integrations

### ISSUE THREAD

**Issue by ConnorDY** [RoadieHQ/roadie-backstage-plugins#188]
If you have multiple GitHub integrations setup in `app-config.yaml` (like shown below), currently this plugin only uses the first one.

```yaml
integrations:
  github:
    - host: github.com
      token:
        $env: GITHUB_TOKEN
    - host: github.domain.com
      apiBaseUrl: https://github.domain.com/api/v3
      token:
        $env: GHE_TOKEN
```

## Feature Suggestion

Add support for multiple GitHub integrations.

## Possible Implementation

I haven't looked at your code yet so I'm not sure.

## Context

We are using Backstage with both public GitHub (github.com) and an enterprise GitHub server.
