### ISSUE TITLE
Entity Validation on a techdocs-ref fails if a sub directory in the URL contains `dir`

### ISSUE THREAD

**Issue by dlaird-ovo** [RoadieHQ/roadie-backstage-plugins#1890]
If I specify a `techdocs-ref` like this:

```
apiVersion: backstage.io/v1alpha1
metadata:
  ...
  annotations:
    backstage.io/techdocs-ref: dir:https://github.com/org/repo/tree/main/apps/example-direct-bug/techdocs
```

then the Entity validator prints
```
Error: Techdocs annotation specifies "dir" but file under catalogue/https/mkdocs.yaml|catalogue/https/mkdocs.yml not found
```

## Expected Behavior

Think it should only check this case if it begins with dir:

## Current Behavior

Entity validator prints
```
Error: Techdocs annotation specifies "dir" but file under catalogue/https/mkdocs.yaml|catalogue/https/mkdocs.yml not found
```

## Steps to Reproduce

Specifiy a `techdofs-ref` containing `dir`

## Your Environment
"@roadiehq/backstage-entity-validator": "^0.5.1",
