### ISSUE TITLE
Argo CD Plugin Card Not Displaying Application Data Despite Valid Setup

### ISSUE THREAD

**Issue by BanerjeeAgniva** [RoadieHQ/roadie-backstage-plugins#1923]
Hi team,

I'm encountering an issue while setting up the Argo CD plugin for Backstage as part of a demo for a prospect. Although the plugin integration appears correctly configured and the Argo CD instance is reachable and synced, the Argo CD card in the entity view remains empty (no application data is rendered).

### 🧪 Observations

* Argo CD UI shows the `guestbook` app is healthy and synced successfully (`https://34.168.103.179`).
* The `catalog-info.yaml` entity is correctly annotated:

  ```yaml
  annotations:
    argocd/app-name: guestbook
  ```
* The plugin instance is configured in `app-config.yaml`:

  ```yaml
  argocd:
    username: admin
    password: ${ARGOCD_PASSWORD}
    appLocatorMethods:
      - type: 'config'
        instances:
          - name: argoInstance1
            url: https://34.168.103.179
            token: ${ARGOCD_AUTH_TOKEN}
  ```
* Secrets (`ARGOCD_AUTH_TOKEN` and `ARGOCD_PASSWORD`) are defined and injected correctly.
* The card in IDP loads with no errors, but no rows appear in the ArgoCD overview section.

### 📸 Screenshots

* Argo CD application view (`guestbook` is healthy and synced):

<img width="1609" alt="Image" src="https://github.com/user-attachments/assets/0464071b-8a52-485b-a9c7-563ba07774ba" />

* IDP service card showing ArgoCD section as empty:

<img width="1496" alt="Image" src="https://github.com/user-attachments/assets/5db9c3aa-5be5-4f52-887b-1038cc6b5d8d" />

* Corresponding `catalog-info.yaml`:

<img width="647" alt="Image" src="https://github.com/user-attachments/assets/11051de0-62db-4998-a896-75a8925acf06" />

* Argo CD plugin config and secrets:
 
<img width="734" alt="Image" src="https://github.com/user-attachments/assets/9cd92cac-9598-4152-9a1f-2e44f3580a12" />

### ✅ Expected

The `guestbook` application should appear in the ArgoCD plugin card for the `agniva-jenkins` service component.

### ⚙️ Versions

* Harness IDP (Backstage-based)
* Argo CD plugin (latest as of June 2025)
* Argo CD instance: v2.x
* YAML config adheres to backstage.io/v1alpha1

---
