### ISSUE TITLE
Is there a reason JIRA plugin must assume Basic Auth for activities? 

### ISSUE THREAD

**Issue by madorb** [RoadieHQ/roadie-backstage-plugins#277]
I'm able to successfully pull back issues with:

```
  '/jira/api':
    target: https://my-jira-instance.com
    headers:
      Authorization: 'Bearer <my-token>'
```

but then when it attempts to get activities: it appears to force the use of basic auth, which, of course, doesn't work as we don't have a basic auth value to send. I tried with basic auth, but could not get it to work at all, just got 401s.

https://github.com/RoadieHQ/roadie-backstage-plugins/blob/6d7c927791118d0bb980207f3dfa4188de9ddfef/plugins/frontend/backstage-plugin-jira/src/api/index.ts#L179

If not, it would be better to clarify in the documentation that basic auth is a hard requirement
