### ISSUE TITLE
[backstage-plugin-jira] Support custom jql queries

### ISSUE THREAD

**Issue by tbourrelovh** [RoadieHQ/roadie-backstage-plugins#387]
We would like to be able to retrieve the number of issues matching a custom JQL query.

## Feature Suggestion

It would be great to be able to provide JQL queries in our entities, alongside the plugin configuration. Those queries would be used to display the number of issues matching them.

## Possible Implementation

I took the liberty to try out a potential implementation, you can see it on my fork : https://github.com/tbourrelovh/roadie-backstage-plugins/commit/12909b06de149e7d9a39881fb6a2027c58227b4b

### Entity configuration

```yaml
metadata:
  ...
  annotations:
    jira/project-key: MYPROJECT
  jira:
    count:
      - title: "P1 & P2"
        query: 'project = MYPROJECT AND issuetype = Incident AND status = Open AND "Application Services DTR" = SERVICE AND Severity in (P1, P2)'
      - title: "P3, P4, P5"
        query: 'project = MYPROJECT AND issuetype = Incident AND status = Open AND "Application Services DTR" = SERVICE AND Severity in (P3, P4, P5)'
      - title: "All bugs"
        query: 'project = MYPROJECT AND issuetype = Bug  AND "Application Services DTR" = SERVICE'
    ...
```

### Display

In term of displaying the data, I thought that it could be added in an another section under the actual count section.

![backstage-plugin-jira custom jql](https://user-images.githubusercontent.com/73471940/150326304-6d06dae2-0fb1-466e-b70a-eec436e75747.png)

## Context

We want to track the number of issues based on custom fields in our jira issues.
