### ISSUE TITLE
TechDocs Validator Uses Wrong Mkdocs Extension

### ISSUE THREAD

**Issue by alexcurtin** [RoadieHQ/roadie-backstage-plugins#426]
Given a catalog-info.yaml like so:

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: demo
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: demo
  lifecycle: production
```
The entity-validator should find the appropriately named `mkdocs.yml` and pass validation, if that file exists at the specified path from the annotation `backstage.io/techdocs-ref:`

## Current Behavior

Instead, the validator throws the below error
`Failed to validate catalog-info.yaml: Error: Techdocs annotation specifies "dir" but file under mkdocs.yaml not found`

## Possible Solution

From reading the official [Mkdocs documentation](https://www.mkdocs.org/getting-started/), the filename that mkdocs expects is `mkdocs.yml` not `mkdocs.yaml` - even though both work. We need to adjust https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/utils/roadie-backstage-entity-validator/src/validator.js#L155 to be an OR statement or just use `mkdocs.yml`
