### ISSUE TITLE
Jira integration - Error 500 

### ISSUE THREAD

**Issue by lduparc** [RoadieHQ/roadie-backstage-plugins#460]
Hi,

I'm trying to deal with an error with Jira plugin. All is working perfectly locally but when I'm deploying backstage on a kubernetes cluster. I've got error 500 with no more details. Quite strange since all is ok when I run backstage locally using yarn using same Basic Token.

Trying to call directly jira api, all is ok.
Checking on jira server, my domain is known.

```
curl -s  -H "Content-Type: application/json" -H "Authorization: ${JIRA_TOKEN}" "http://localhost:7007/api/proxy/jira/api/rest/api/latest/project/XYZ"

-> working
```

```
curl -s  -H "Content-Type: application/json" -H "Authorization: ${JIRA_TOKEN}" "https://jira.xxxxx.com/rest/api/latest/project/XYZ"

-> working
```

```
curl -s  -H "Content-Type: application/json" -H "Authorization: ${JIRA_TOKEN}" "https://myk8sdomain.com/api/proxy/jira/api/rest/api/latest/project/XYZ"

-> FAILED -> Error 500 - Error occurred while trying to proxy 
[EPROTO] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

here config used locally and remotely: 

```
proxy:
  '/jira/api':
    target: 'https://jira.xxxx.com'
    headers:
      Authorization:
        $env: JIRA_TOKEN
      Accept: 'application/json'
      Content-Type: 'application/json'
      X-Atlassian-Token: 'no-check'
      User-Agent: "ANYRANDOMSTRINGS"
```
