### ISSUE TITLE
Buildkite Plugin: 404 on "wait: ~" steps in Pipeline

### ISSUE THREAD

**Issue by alecjacobs5401** [RoadieHQ/roadie-backstage-plugins#536]
When using the `@roadiehq/backstage-plugin-buildkite`, navigating to a specific build path (enabled in https://github.com/RoadieHQ/roadie-backstage-plugins/commit/1a2208929e2d05006a0f2da9f7f6bb4691272f1f) causes 404 error notifications when the Buildkite Pipeline being loaded includes `wait: ~` steps.

Example Buildkite Pipeline File
```yaml
steps:
  - label: Build
    commands:
      - make build

  - wait: ~

  - label: After Wait To Show 404 Issue
    agents:
        queue: v1
    commands:
      - echo "demo"
```

## Expected Behavior
The Buildkite Plugin Specific Build page for an Entity should properly display a build step for `wait: ~` steps

## Current Behavior
Buildkite Pipelines that include "wait" steps cause 404 errors

![image](https://user-images.githubusercontent.com/12898497/167909841-c59a9fe7-0ac3-4c16-9cc7-cdce85845171.png)

## Steps to Reproduce

These steps assume a configured environment and are run locally

1. Create Buildkite pipeline that includes a wait step (see example above)
2. Import Entity with proper Buildkite annotation for that pipeline
3. Navigate to `CI/CD` tab on Entity Page
4. Click into a specific build
5. See 404 where `wait` step should be

## Possible Solution

Handle Pipeline steps that do not have log output / labels (potential fix for the 404 errors)

## Context

* There are no server logs or console logs that show anything but a 404 error

## Your Environment

- Backstage version: `1.1.1`
- `@backstage/plugin-catalog-react` version: `1.0.1`
- `@backstage/integration` version: `1.1.0`
- `@roadiehq/backstage-plugin-buildkite` version: `2.0.3`
