### ISSUE TITLE
http requests scaffolder action: do not set authorization header if that already presents

### ISSUE THREAD

**Issue by artemiyokulov** [RoadieHQ/roadie-backstage-plugins#558]
## Feature Suggestion

if i'm already auth in backstage, and set custom authorization header in scaffolder action input parameters, requests completed with incorrect header, because this "if" do not check presents header ( https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/scaffolder-actions/scaffolder-backend-module-http-request/src/actions/run/backstageRequest.ts#L130)

## Possible Implementation

Maybe replace if with 
```
if (token && !httpOptions?.headers['authorization'])
```

## Context
https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/scaffolder-actions/scaffolder-backend-module-http-request/src/actions/run/backstageRequest.ts#L130

**Comment by kissmikijr** [comment]
I am not sure I tottaly understand what is happening, how can you set authorization headers already? Can you link me the scaffolder template where you set it ?

**Comment by artemiyokulov** [comment]
```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: template.gitlab-actions.dx.x5.ru
  title: Gitlab Action Template
  description: Create new gitlab action quickly from this template
  tags:
    - action
    - gitlab-action
    - ci-cd
    - template
spec:
  owner: dx-team
  type: library

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Авторизация в GitLab
      required:
        - gitlab_user_info
      properties:
        gitlab_user_info:
          title: gitlab oauth
          type: object
          description: Auth in gitlab
          properties:
            token:
              type: string
            userEmail:
              type: string
            userName:
              type: string
          required:
            - token
            - userEmail
            - userName
          ui:autofocus: true
          ui:field: GitlabOauthField

 ...

  steps:
...

    - id: setup_component_badge
      name: Setup Backstage::component badge
      action: http:backstage:request
      input:
        method: 'POST'
        headers:
          Authorization: "Bearer ${{ parameters.gitlab_user_info.token }}"
        path: '/api/proxy/gitlab-oauth/projects/${{ steps.publish.output.projectId }}/badges'
        params:
          link_url: 'https://backstage.x5.ru/catalog/default/component/${{ parameters.name }}.gitlab-actions.dx.x5.ru'
          image_url: "https://git-badges.x5.ru/static/v1?label=Backstage&message=component&color=green"
          name: 'backstage_component'

...
```

We use custom component for auth in gitlab as OIDC provider. After that we use token in http requests
