### ISSUE TITLE
ArgoCD - app-selector must be URL-encoded if it contains a slash

### ISSUE THREAD

**Issue by noisyscanner** [RoadieHQ/roadie-backstage-plugins#586]
When using the `argocd/app-selector` annotation to select multiple apps with a label, if the label contains a slash, eg `mycompany.com/service-name=my-service`, this will result in a 404 from the backend.

## Expected Behavior
It works without throwing a 404, by automatically URL-encoding the annotation value. In the case above, it would become `mycompany.com%2Fservice-name%3Dmy-serivce`

## Current Behavior
The backend returns a 404, and the frontend shows the below error.
<img width="359" alt="image" src="https://user-images.githubusercontent.com/627654/178536053-7f1b772e-0bb2-4768-ba79-8907f1c7fcc2.png">

## Steps to Reproduce
Register this component and go to its `EntityPage`, containing the `EntityArgoCDOverviewCard`. 
```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api-thing
  annotations:
    argocd/app-selector: 'mycompany.com/service-name=api-thing'
spec:
  type: service
  lifecycle: production
```

## Possible Solution

A workaround is to re-assign the annotation by using `encodeURIComponent` in `EntityPage.tsx` to replace the slash with `%2F`.
Ideally this should be done internally by the FE plugin.

## Your Environment

Frontend
```json
    "@backstage/plugin-catalog-react": "^1.1.1",
    "@roadiehq/backstage-plugin-argo-cd": "^2.1.4",
```

Backend
```json
    "@backstage/integration": "^1.2.1",
    "@roadiehq/backstage-plugin-argo-cd-backend": "^2.4.1",
```
