### ISSUE TITLE
[plugin/catalog-backend-module-okta] - Missing required config value at 'orgUrl'

### ISSUE THREAD

**Issue by andreaspoldi** [RoadieHQ/roadie-backstage-plugins#644]
## Expected Behavior
issuing 'yarn dev' for app start, the startup process goes through without errors and the app is accessible

## Current Behavior

backend startup returns this kind of error :

`[1] Backend failed to start up Error: Missing required config value at 'orgUrl'`

although app-config.yaml has the proper setup 

```yaml
catalog:
  providers:
    okta:
      orgUrl: 'https://trial-xxxxxxx.okta.com/'
      token:
        $env: ****************************************
```

## Steps to Reproduce

- create Okta trial account
- create new backstage app via **npx @backstage/create-app**
- follow README.md at https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/backend/catalog-backend-module-okta/README.md
- yarn dev

## Your Environment

vanilla backstage setup done via npx @backstage/create-app, version 1.5.0

**Comment by martina-if** [comment]
Hi @andreaspoldi, when I look at the example config in that README the `orgUrl` part is in a list with a dash:

```
catalog:
  providers:
    okta:
      - orgUrl: 'https://tenant.okta.com'
...
```

Could that be the issue?
