### ISSUE TITLE
Jira Plugin : Request results in error 400 

### ISSUE THREAD

**Issue by A1essandra** [RoadieHQ/roadie-backstage-plugins#693]
We want to implement Jira plugin in our Backstage instance but when we do the implementation the Jira card is not filled because of an error 400.

## Expected Behavior

The Jira card should be filled with data from our Jira instance.

## Current Behavior

When http://localhost:7007/api/proxy/jira/api/rest/api/3/search request is used, we have an error 400 message in the Jira card.
![image](https://user-images.githubusercontent.com/116367535/197222305-20249c5f-d20e-492e-9ef6-280a0f54547a.png)
The error message is ```"The value 'Task' does not exists for the field 'issuetype'."```

## Context

app-config.yaml
```
backend:
  csp:
    img-src:
      - "'self'"
      - 'data:'
      - 'JIRA_URL'

proxy:
  '/jira/api':
    target: <JiraUrl>
    headers:
      Authorization: "Basic <token>"
      Accept: 'application/json'
      Content-Type: 'application/json'
      X-Atlassian_Token: 'no-check'
      User-Agent: 'Test'

jira:
  proxyPath: /jira/api
  apiVersion: 3
```

## Your Environment

- `"@roadiehq/backstage-plugin-jira": "^2.1.2"`
- Backastage version: 1.3.0
