### ISSUE TITLE
Does roadie scaffolder-backend-module-http-request support authorization in headers?

### ISSUE THREAD

**Issue by subash54** [RoadieHQ/roadie-backstage-plugins#746]
### Discussed in https://github.com/RoadieHQ/roadie-backstage-plugins/discussions/745

<div type='discussions-op-text'>

<sup>Originally posted by **subash54** November 30, 2022</sup>
Hi Team I am using **roadie scaffolder-backend-module-http-request** to call api which has authentication

```
 - id: backstage_request_with_input
      name: backstage request
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/api/proxy/sheet/test'
      headers:
        Authorization: 'Basic c3ViYXNoOmhlbGxv'
```
The above is the body that I am passing but I am getting unauthorized  while passing authorization in headers.

In Postman for the same I am able to send the request.

Whether it supports passing authorization in headers.

 Can anyone help me in this?
       </div>
