### ISSUE TITLE
Unable to pass xml as a body in scaffolder-backend-module-http-request

### ISSUE THREAD

**Issue by subash54** [RoadieHQ/roadie-backstage-plugins#747]
Hi Team I am trying to make a post request to Jenkins which takes XML as a body.
```
id: backstage_request_with_input
name: backstage request
action: http:backstage:request
input:
   method: 'POST'
   path: "/api/proxy/test
   body:
       data: 'xml content'
          
```

I if pass XML content like this It is sending a request with key-value pair as a body but instead I need to send only the value not the key.

```

      if (
        input.body &&
        input.headers &&
        input.headers['content-type'] &&
        input.headers['content-type'].includes('application/json')
      ) {
        inputBody = JSON.stringify(input.body);
      } else {
        inputBody = input.body;
      }
```

The Above is the code snippet of the scaffolder-backend-module-http-request so it is taking key value pair as the body.

Can anyone help me to send the value only?

or Is it possible to change the type of the body to accept both string and object like this
```
 body: {
            title: 'Request body',
            description: 'The body you would like to pass to your request',
            type: ['object','string']
          },
```
So I can send my XML content in the body like this

` body: 'XML content'`    
     
   instead of   
```   
body:
       data: 'xml content'
```
