### ISSUE TITLE
Github Insights languages card crashing page

### ISSUE THREAD

**Issue by MikeSamv** [RoadieHQ/roadie-backstage-plugins#761]
The page crashes when trying to use the languages card inside `@roadiehq/backstage-plugin-github-insights`.

## Expected Behavior

The expected behavior would be to not have any errors when using the `<EntityGithubInsightsLanguagesCard />` component.

## Current Behavior

Using the `<EntityGithubInsightsLanguagesCard />` component causes the page to crash with error 
```
undefined is not an object (evaluating 'Object.keys(value)')
```

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/102695183/206656310-c87dfd7e-e619-4ad6-8eeb-805eacff0d56.png">

## Steps to Reproduce

1. Create a fresh Backstage app
```
npx @backstage/create-app
```

2. Install the plugin
```
cd packages/app
yarn add @roadiehq/backstage-plugin-github-insights
```

3. Add plugin to the entity page
```
// packages/app/src/components/catalog/EntityPage.tsx
import { isGithubInsightsAvailable, EntityGithubInsightsLanguagesCard, EntityGithubInsightsReleasesCard } from '@roadiehq/backstage-plugin-github-insights';

...

const overviewContent = (
  ...
  <EntitySwitch>
    <EntitySwitch.Case if={e => Boolean(isGithubInsightsAvailable(e))}>
      <Grid item md={12} xs={12}>
        <EntityGithubInsightsLanguagesCard />
      </Grid>
    </EntitySwitch.Case>
  </EntitySwitch>
  ...
);
```

4. Update example-website with a Github repo annotation
```
// examples/entities.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
  annotations:
    github.com/project-slug: backstage/backstage
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
```

5. Start Backstage
```
yarn dev
```

6. Visit the `example-website` component page
http://localhost:3000/catalog/default/component/example-website

7. Reject GitHub login prompt

8. Observe page crashes

## Context

I am noticing this issue when I try to update Backstage from version 1.7.x to 1.8.x.

## Your Environment

- `@backstage/plugin-catalog-react` version: 1.2.1
- `@backstage/integration` version: 1.4.0
