### ISSUE TITLE
josnata action dose not work

### ISSUE THREAD

**Issue by wesky93** [RoadieHQ/roadie-backstage-plugins#799]
## Expected Behavior

```
- id: edit-deploymen
  name: 레플라키 개수 필드 제거
  action: roadiehq:utils:jsonata
  input:
    data: ${{ steps.parsefile.output.content }}
    expression: '$ ~> | $.spec | {} , ["replicas"] |'
```
I want to remove the replica from the deployment, but the result is null.

## Steps to Reproduce

```
steps:
    - id: edit-deployment
      name: test
      action: roadiehq:utils:jsonata
      input:
        data:
          abc: 'test'
          spec:
            replicas: 3
            test: test
        expression: '$ ~> | $.spec | {} , ["replicas"] |'
    - id: debug-edit
      name: Debug
      action: debug:log
      input:
        extra: ${{ steps.edit-deployment.output.result }}
```

The results are as follows
```
[1](http://localhost:3000/create/tasks/30adf672-c7cd-463f-ab91-41bfc618acc0#line-1)2022-12-26T07:01:06.000Z Beginning step Debug[2](http://localhost:3000/create/tasks/30adf672-c7cd-463f-ab91-41bfc618acc0#line-2)2022-12-26T07:01:06.000Z info: {[3](http://localhost:3000/create/tasks/30adf672-c7cd-463f-ab91-41bfc618acc0#line-3)  "extra": null[4](http://localhost:3000/create/tasks/30adf672-c7cd-463f-ab91-41bfc618acc0#line-4)}[5](http://localhost:3000/create/tasks/30adf672-c7cd-463f-ab91-41bfc618acc0#line-5)2022-12-26T07:01:06.000Z Finished step Debug
```

However, on the jsonata site, you can see that only the replica field has been removed.

![2022-12-26_16-07-08](https://user-images.githubusercontent.com/5326335/209515960-a7275265-62ba-4d2c-8868-fc5cc60e57e0.png)

## Possible Solution

In the official document of jsonata,
It says to use await,
It seems to be caused by not using wait in the source code. 

```
const jsonata = require('jsonata');

const data = {
    example: [
        {value: 4},
        {value: 7},
        {value: 13}
    ]
};

(async () => {
    const expression = jsonata('$sum(example.value)');
    const result = await expression.evaluate(data);  // returns 24
})()
```

## Your Environment

- `@roadiehq/scaffolder-backend-module-utils` version: "^1.7.0"
