### ISSUE TITLE
Customize ArgoCD plugin to visualize chart and appVersion

### ISSUE THREAD

**Issue by arnouthoebreckx** [RoadieHQ/roadie-backstage-plugins#809]
## Feature Suggestion

The ArgoCD plugin currently visualizes the sync/health status and last synced. I suggest adding a chart and version column that respectively represent the full chart name and application version. ArgoCD allows insights into the managed resources of an application and this can be used to scrape data from labels.

![image](https://user-images.githubusercontent.com/24568583/211036869-ad123db3-533a-494f-86b4-518d102eabf1.png)

Suggestion is heavily tinted towards the usage of the Helm kind in ArgoCD. However suggestions are welcome that are more generic and implementable on each method.

## Possible Implementation  

ArgoCD has an API endpoint `/api/v1/applications/{applicationName}/managed-resources` that returns all the resources managed by the ArgoCD application including their entire specification. This can be used to search for labels that are set on the resources.

Helm by default applies certain labels if you have a chart and appVersion defined in the Chart.yaml (https://helm.sh/docs/chart_best_practices/labels/#standard-labels). These would be the default labels to look for if this feature is activated and could then be visualized in the view.

helm.sh/chart --> Chart name + chart version
app.kubernetes.io/version --> appVersion

I would suggest a configuration that would look like this:

```
argocd:
  versions:
    # This will setup the configuration to follow the helm standard and also display chart version
    helm: true 
    # If you do not want to use the default recommended labels you can define your own here
    custom:
       app-version: <insert-custom-label-here>
    # The ArgoCD API allows filtering on Kind when calling the resources, it's more performant to only search on certain resources and definitely if you are sure that it's always present in your ArgoCD application.
    resources:
      - Serviceaccount
      - Secrets
      - Deployment
      - StatefulSet
``` 

## Context

The general goal is to allow a bit more in-depth view into the versions that your components are running from Backstage. Currently we have to look in Git or in ArgoCD to actually know this data.
