### ISSUE TITLE
Argocd Multiple Instances

### ISSUE THREAD

**Issue by marct83** [RoadieHQ/roadie-backstage-plugins#832]
I can't find any documentation on how to have one component show argocd status from two different argocd instances. We have a staging cluster and a production cluster. I would like to show both argocd deployments in a single component in backstage. Is this possible? If yes how?

**Comment by martina-if** [comment]
Hi @marct83 , is this what you are looking for? https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/backend/backstage-plugin-argo-cd-backend#argo-cd-plugin-backend-for-backstage 

I can see how these are not super easy to find and we may need to surface these from the top level readme..

**Comment by marct83** [comment]
I don't think so. If I'm understanding that correctly it's for setting up the plugin for multiple instances, but I don't see any mention of using multiple instances in the same component or how you would define that in a catalog-info.yaml. Actually I don't see any explanation about how a catalog-info.yaml should be setup for a component using the backend plugin.

**Comment by lmcgartland** [comment]
I followed the instructions for multiple instances option 2 (so i could display argocd info for multiple clusters for one catalog entry) however, the API response from the backend is returning []. Is there a missing step to get multi clusters configured?

**Comment by martina-if** [comment]
Hi both, apologies because we don't have that much experience in the team running this plugin ourselves perhaps @karlhaworth can shed some light here?

**Comment by karlhaworth** [comment]
@marct83 Below is a sample `catalog-info.yaml` file.

```yaml
metadata:
  name: test-app
  description: 'test-app'
  annotations:
    argocd/app-selector: 'backstage-name=test-app'
```

Below is how we have the configuration for the clusters and the argo section.

```yaml
argocd:
  username: ${ARGOCD_USERNAME_TEST}
  password: ${ARGOCD_PASSWORD_TEST}
  appLocatorMethods:
    - type: 'config'
      instances:
        - name: test-cluster-001-eastus
          url: https://argocd-test-cluster-001-eastus.argocd.svc.8080.mesh
kubernetes:
  apiVersionOverrides:
    cronjobs: 'v1beta1'
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://master-rke.rancher.svc.8080.mesh/k8s/clusters/t-57vh3
          name: test-cluster-001-eastus
          authProvider: 'serviceAccount'
          serviceAccountToken: ${TEST_TOKEN}
```

@lmcgartland The API response being `[]` could be due to labels not properly set on the argo side?

Does this help either of you? I'd be happy to help/chat more about this.

**Comment by marct83** [comment]
> @marct83 Below is a sample `catalog-info.yaml` file.
> 
> ```yaml
> metadata:
>   name: test-app
>   description: 'test-app'
>   annotations:
>     argocd/app-selector: 'backstage-name=test-app'
> ```
> 
> Below is how we have the configuration for the clusters and the argo section.
> 
> ```yaml
> argocd:
>   username: ${ARGOCD_USERNAME_TEST}
>   password: ${ARGOCD_PASSWORD_TEST}
>   appLocatorMethods:
>     - type: 'config'
>       instances:
>         - name: test-cluster-001-eastus
>           url: https://argocd-test-cluster-001-eastus.argocd.svc.8080.mesh
> kubernetes:
>   apiVersionOverrides:
>     cronjobs: 'v1beta1'
>   serviceLocatorMethod:
>     type: 'multiTenant'
>   clusterLocatorMethods:
>     - type: 'config'
>       clusters:
>         - url: https://rancher-test.rancher.svc.8080.mesh/k8s/clusters/t-57vh3
>           name: test-cluster-001-eastus
>           authProvider: 'serviceAccount'
>           serviceAccountToken: ${TEST_TOKEN}
> ```
> 
> @lmcgartland The API response being `[]` could be due to labels not properly set on the argo side?
> 
> Does this help either of you? I'd be happy to help/chat more about this.

I'm not sure it does. So if I was to add another instance in the argocd section of the app-config would both instances show in the component in the UI? Ie. stagging instance and prod instance.

**Comment by karlhaworth** [comment]
> I'm not sure it does. So if I was to add another instance in the argocd section of the app-config would both instances show in the component in the UI? Ie. stagging instance and prod instance.

yes. the selectors just have to match and not be based on env in the catalog yaml and in the argo labels section.

![image](https://user-images.githubusercontent.com/58607256/217649636-41d76ba6-4546-4011-bc5b-e2c7f1a89232.png)

**Comment by weslers** [comment]
Hey everyone, also having the same issue. Have the labels set in both places and get "No records to display" via the component. Just wondering if anyone found a solution to this...

#### ArgoCD
<img width="492" alt="Screenshot 2023-02-24 at 20 31 44" src="https://user-images.githubusercontent.com/1480002/221285642-0f45d2f6-7adc-4d5b-98b3-03c3370ec5a1.png">

#### catalog.yaml
<img width="337" alt="Screenshot 2023-02-24 at 20 32 27" src="https://user-images.githubusercontent.com/1480002/221285741-44def41f-ad03-441b-991f-ab7e01bd4569.png">

#### Component screen
<img width="515" alt="Screenshot 2023-02-24 at 20 30 40" src="https://user-images.githubusercontent.com/1480002/221285486-abea7d2f-0a32-4626-bfdd-9a2d1ea0790f.png">

**Comment by weslers** [comment]
I can also confirm making a GET request to `https://my-argocd.com/api/v1/applications?backstage-name%3Dtest-demo` does return an items array with the expected applications.

**Comment by weslers** [comment]
I have tested making a GET request to `https://example-argocd.net/api/v1/applications?selector=backstage-name%3Dtest-demo` and it does return the expected applications in the items array.

**Comment by karlhaworth** [comment]
@weslers if you want to make a screenshare session this week we can. Then we can try to figure out the problem.

**Comment by weslers** [comment]
@karlhaworth yea that would be great

**Comment by weslers** [comment]
@karlhaworth I just sent you a message via LinkedIn we can arrange something there and passed on my email

**Comment by weslers** [comment]
Quick follow after the screen share session with @karlhaworth with 2 points to note for anyone who may be having a similar issue.

1. ArgoCD tokens do not seem to work when making a request to Argo. Username and password do work. Tested this with @karlhaworth and is aware of that issue
2. When testing with a local instance of ArgoCD you will need to it with the `--insecure` flag to stop the HTTPS redirection and allow GET request. If installing ArgoCD locally via helm you can pass in `--insecure-skip-tls-verify`. Or you can modify the deployment command of `argocd-server` to be as follows:

```

**Comment by karlhaworth** [comment]
@marct83 did you can to screenshare by chance to solve your issue? Do the answers above help at all?

**Comment by weslers** [comment]
@karlhaworth should the `Open ArgoCD Dashboard` button appear when using the multiple instance options?

Looking through `DetailsDrawer.ts` I found `href={`${baseUrl}/applications/${rowData.metadata?.instance?.name}`}` but if you don't set `baseUrl` under `argocd.baseUrl` this button won't appear. If you do set this then all applications will use the one `baseUrl` value and not its own instance `url` as the link for the button.

For example, if I have 3 environments the `url` should be different for each of those buttons depending on which application I click on and loads within the `DetailsDrawer` component.

<img width="398" alt="Screenshot 2023-03-01 at 21 22 32" src="https://user-images.githubusercontent.com/1480002/222268524-28b8d33a-be31-4a85-b5eb-8d11ba6f1972.png">

**Comment by marct83** [comment]
Sorry for the delay. 

I'm seeing this error now:

 Error: failed to fetch data, status 500: Internal Server Error : cannot find an argo instance to match this cluster

I created a user/pass in argo. Tested it works with https://lab-argocd.test/api/v1/session.

Config looks like:

``` yaml
argocd:
  waitCycles: 25
  appLocatorMethods:
    - type: 'config'
      instances:
        - name: argoInstance1
          url: https://lab-argocd.test
          username: ${ARGOCD_USER} # optional
          password: ${ARGOCD_PASS} # optional
```

Do I need to have the kubernetes cluster config? If yes the docs are way off.
