### ISSUE TITLE
Action to get date when steps are ran

### ISSUE THREAD

**Issue by OneCricketeer** [RoadieHQ/roadie-backstage-plugins#962]
## Feature Suggestion

Create an action with an output value that can return the date when the scaffolder ran. 

## Possible Implementation

```yml
steps: 
 - id: get-date
   action: calendar:today

 - id: Render template
    action: fetch:template
    input:
      values: 
        generationDate: ${{ steps['get-date'].output.date }}  # use output from above step
```

... in template

```none
Created on ${{ values.generationDate }} by Backstage. 
```

## Context

Scaffolder templates are more-or-less static assets. They can change over time, meanwhile the earlier created codebases become more and more out of date. 

This request is to get some metadata available as to when the template was originally created, to aid in code-discovery and support for end-users of the templates we provide.
